### ISSUE TITLE
Error: Not found

### ISSUE THREAD

**Issue by arhue** [avakar/set-deployment-status#8]
Couple of days back GitHub changed something in their API. After which, this Action is failing. I tried v1 and master.

```
    - name: Set deployment status to in_progress - k8sslack
      uses: avakar/set-deployment-status@master
      with:
        state: in_progress
        log_url: "https://github.com/tectonic/awardforce/commit/${{ github.sha }}/checks"
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TECHDEPLOY_TOKEN }}
      if: github.event.deployment.payload.deployment == 'yes'
```

```
Run avakar/set-deployment-status@master
  with:
    state: in_progress
    log_url: https://github.com/tectonic/awardforce/commit/42b25037db71f00a59d685a1b3a5776a5b4c63ac/checks
    auto_inactive: true
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    S3_ACCESS_KEY: ***
    S3_SECRET_KEY: ***
    GITHUB_TOKEN: ***
/usr/bin/docker exec  bf9ea7a087ccee7b64476cd4a760de841e0c2b9743b22b992581d71da896af15 sh -c "cat /etc/*release | grep ^ID"
Error: Not Found
```

Seems to be related to this: https://github.com/ad-m/github-push-action/issues/76
